---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update"]
- apiGroups: ["kubevirt.io"]
  resources: ["kubevirts"]
  verbs: ["get", "patch"]
