---
apiVersion: v1
data:
  cloudInit: |
    #cloud-config
    packages:
    - open-iscsi
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/description: iSCSI initiator tool Cloud Config Template
  labels:
    harvesterhci.io/cloud-init-template: user
    {{- include "labels" $ | nindent 4 }}
  name: iscsi-initiator-tool
  namespace: harvester-public
---
apiVersion: v1
data:
  cloudInit: |
    #cloud-config
    chpasswd:
      expire: False
    password: ...
    ssh_pwauth: True
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/description: Password Cloud Config Template
  labels:
    harvesterhci.io/cloud-init-template: user
    {{- include "labels" $ | nindent 4 }}
  name: password
  namespace: harvester-public
{{- range $vendorId, $vendor := $.Values.fpga.vendors }}
{{- range $deviceId, $device := $vendor.devices }}
---
apiVersion: v1
data:
  cloudInit: |
    #cloud-config
    inaccel:
      {{ $vendorId }}/{{ $deviceId }}: ...
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/description: {{ $vendor.name }} {{ $device.name }} Cloud Config Template
  labels:
    harvesterhci.io/cloud-init-template: user
    {{- include "labels" $ | nindent 4 }}
  name: {{ kebabcase ( print $vendorId "-" $deviceId ) }}
  namespace: harvester-public
{{- range $variantId, $variant := $device.variants }}
---
apiVersion: v1
data:
  cloudInit: |
    #cloud-config
    inaccel:
      {{ $vendorId }}/{{ $deviceId }}: ...
    write_files:
    - content: {{ $variantId }}
      path: /etc/fpga-variant
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/description: {{ $vendor.name }} {{ $variant.name }} Cloud Config Template
  labels:
    harvesterhci.io/cloud-init-template: user
    {{- include "labels" $ | nindent 4 }}
  name: {{ kebabcase ( print $vendorId "-" $variantId ) }}
  namespace: harvester-public
{{- end }}
{{- end }}
{{- end }}
