{{- range $subnetworkId, $subnetwork := $.Values.networks.vlan.subnetworks }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    field.cattle.io/description: {{ $.Values.networks.vlan.name }} {{ $subnetwork.name }} Network
    helm.sh/resource-policy: keep
    network.harvesterhci.io/route: '{"mode":"auto"}'
  labels:
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "{{ $subnetwork.id }}"
    {{- include "labels" $ | nindent 4 }}
  name: vlan-{{ kebabcase $subnetworkId }}
  namespace: harvester-public
spec:
  config: '{"cniVersion":"0.3.1","name":"vlan-{{ kebabcase $subnetworkId }}","type":"bridge","bridge":"harvester-br0","promiscMode":true,"vlan":{{ $subnetworkId }},"ipam":{}}'
{{- end }}
