---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: cloud-init
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Chart.Name }}-cloud-init
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: 443
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: cloud-init
    kind: Deployment
    {{- include "selectorLabels" $ | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kubevirt-hack
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Chart.Name }}-kubevirt-hack
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: 443
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: kubevirt-hack
    kind: Deployment
    {{- include "selectorLabels" $ | nindent 4 }}
