{{- range $imageId, $image := $.Values.images }}
---
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/image-name: {{ $image.name }} [{{ date "Mon Jan _2 15:04:05 2006" now }}]
    helm.sh/resource-policy: keep
  labels:
    harvesterhci.io/image-type: {{ trimPrefix "." ( ext $image.url ) }}
    harvesterhci.io/os-type: {{ $imageId }}
    {{- include "labels" $ | nindent 4 }}
  name: {{ kebabcase $imageId }}-{{ lower ( randAlphaNum 5 ) }}
  namespace: harvester-public
spec:
  displayName: {{ $image.name }} [{{ date "Mon Jan _2 15:04:05 2006" now }}]
  sourceType: download
  url: {{ $image.url }}
{{- end }}
{{- range $vendorId, $vendor := $.Values.fpga.vendors }}
{{- range $deviceId, $device := $vendor.devices }}
{{- range $imageId, $image := $device.images }}
---
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/image-name: {{ $vendor.name }} {{ $device.name }} {{ $image.name }} [{{ date "Mon Jan _2 15:04:05 2006" now }}]
    helm.sh/resource-policy: keep
  labels:
    harvesterhci.io/image-type: {{ trimPrefix "." ( ext $image.url ) }}
    harvesterhci.io/os-type: {{ $imageId }}
    {{- include "labels" $ | nindent 4 }}
  name: {{ kebabcase ( print $vendorId "-" $deviceId "-" $imageId ) }}-{{ lower ( randAlphaNum 5 ) }}
  namespace: harvester-public
spec:
  displayName: {{ $vendor.name }} {{ $device.name }} - {{ $image.name }} [{{ date "Mon Jan _2 15:04:05 2006" now }}]
  sourceType: download
  url: {{ $image.url }}
{{- end }}
{{- end }}
{{- end }}
