{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-license
  namespace: kube-system
stringData:
  CORAL_LICENSE_KEY: {{ .Values.license }}
type: Opaque
{{- end }}
