annotations:
  artifacthub.io/images: |
    - image: inaccel/cloud-init:latest
      name: cloud-init
    - image: inaccel/kubevirt-hack:latest
      name: kubevirt-hack
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.inaccel.com
    - name: Support
      url: https://github.com/inaccel/helm/issues
  artifacthub.io/signKey: |
    fingerprint: 468AFD97D42F5E3CD2D58F0B49854F08ECA79B4E
    url: https://keybase.io/inaccel/pgp_keys.asc
  category: Infrastructure
apiVersion: v2
appVersion: "1.0.3"
description: Simplifying FPGA management in Harvester
home: https://inaccel.com
icon: https://gravatar.com/avatar/86a385a9d4ca0ccdfb2ed637cf9f3308
keywords:
- fpga
- infrastructure
maintainers:
- email: info@inaccel.com
  name: InAccel
name: fpga-cloud
sources:
- https://docs.inaccel.com
- https://github.com/inaccel/helm
type: application
version: 1.0.0
