coral:
  image: inaccel/coral
  pullPolicy: Always
  # resources: ...
  # tag: ...

# license: ...

monitor:
  image: inaccel/monitor
  # port: ...
  # pullPolicy: ...
  # resources: ...
  tag: latest

# nodeSelector: ...
