name: release
on:
  push:
    branches:
    - master
    paths:
    - charts/**
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Set up Helm
      uses: azure/setup-helm@v1
    - name: Release charts
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
